
CREATE TABLE pages
(
	"id" INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	"text" TEXT
);
CREATE TABLE users (
  "id" INT NOT NULL AUTO_INCREMENT,
  "user" VARCHAR(255) NOT NULL,
  "pw" VARCHAR(255) NOT NULL,
  PRIMARY KEY ("id"));

